<a href="https://colab.research.google.com/github/SoheliPaul/Machine-Learning/blob/main/MLCIA2_2348561.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('/content/2015 - 2015.csv')

In [3]:
data.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [4]:
data.count()

Country                          158
Region                           158
Happiness Rank                   158
Happiness Score                  158
Standard Error                   158
Economy (GDP per Capita)         158
Family                           158
Health (Life Expectancy)         158
Freedom                          158
Trust (Government Corruption)    158
Generosity                       158
Dystopia Residual                158
dtype: int64

In [6]:
data.shape

(158, 12)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [8]:
data.isnull()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
153,False,False,False,False,False,False,False,False,False,False,False,False
154,False,False,False,False,False,False,False,False,False,False,False,False
155,False,False,False,False,False,False,False,False,False,False,False,False
156,False,False,False,False,False,False,False,False,False,False,False,False
157,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
data.isna().sum()

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [10]:
data.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [14]:
bins=[0,4,6,10]
labels =['Low Happiness','Medium Happiness','High Happiness']
data['Happiness Category']=pd.cut(data['Happiness Score'],bins,labels=labels)

In [17]:
data.tail(15)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Happiness Category
143,Niger,Sub-Saharan Africa,144,3.845,0.03602,0.06940,0.77265,0.29707,0.47692,0.15639,0.19387,1.87877,Low Happiness
144,Cambodia,Southeastern Asia,145,3.819,0.05069,0.46038,0.62736,0.61114,0.66246,0.07247,0.40359,0.98195,Low Happiness
145,Tanzania,Sub-Saharan Africa,146,3.781,0.05061,0.28520,1.00268,0.38215,0.32878,0.05747,0.34377,1.38079,Low Happiness
146,Madagascar,Sub-Saharan Africa,147,3.681,0.03633,0.20824,0.66801,0.46721,0.19184,0.08124,0.21333,1.85100,Low Happiness
147,Central African Republic,Sub-Saharan Africa,148,3.678,0.06112,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230,Low Happiness
148,Chad,Sub-Saharan Africa,149,3.667,0.03830,0.34193,0.76062,0.15010,0.23501,0.05269,0.18386,1.94296,Low Happiness
149,Guinea,Sub-Saharan Africa,150,3.656,0.03590,0.17417,0.46475,0.24009,0.37725,0.12139,0.28657,1.99172,Low Happiness
150,Ivory Coast,Sub-Saharan Africa,151,3.655,0.05141,0.46534,0.77115,0.15185,0.46866,0.17922,0.20165,1.41723,Low Happiness
151,Burkina Faso,Sub-Saharan Africa,152,3.587,0.04324,0.25812,0.85188,0.27125,0.39493,0.12832,0.21747,1.46494,Low Happiness
152,Afghanistan,Southern Asia,153,3.575,0.03084,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,1.95210,Low Happiness
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042,Low Happiness
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328,Low Happiness
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,Low Happiness
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,Low Happiness
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,Low Happiness

In [18]:
transactions=data.Region
encoded=pd.get_dummies(pd.DataFrame(transactions)).sum(level=0)
encoded

<ipython-input-18-060617f50d3f>:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  encoded=pd.get_dummies(pd.DataFrame(transactions)).sum(level=0)

,Region_Australia and New Zealand,Region_Central and Eastern Europe,Region_Eastern Asia,Region_Latin America and Caribbean,Region_Middle East and Northern Africa,Region_North America,Region_Southeastern Asia,Region_Southern Asia,Region_Sub-Saharan Africa,Region_Western Europe
0,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
153,0,0,0,0,0,0,0,0,1,0
154,0,0,0,0,0,0,0,0,1,0
155,0,0,0,0,1,0,0,0,0,0
156,0,0,0,0,0,0,0,0,1,0
157,0,0,0,0,0,0,0,0,1,0

In [44]:
from sklearn.feature_selection import chi2
X=encoded
Y=data['Happiness Rank']
chi_scores=chi2(X,Y)
chi_scores
chi_values=pd.Series(chi_scores[0],index=X.columns)
chi_values.sort_values(ascending=False,inplace=True)
chi_values.plot.bar()

from scipy.stats import chi2_contingency
chi2,p_value,dof,expected=chi2_contingency(chi_scores)
alpha=0.05
if p_value<=alpha:
  print('Null hypothesis is rejected,there is a significant relationship between Happiness and Region')
else:
    print('Null hypothesis cannot be rejected,there is no significant relationship between Happiness and Region')

p_values=pd.Series(chi_scores[1],index=X.columns)
p_values.sort_values(ascending=False,inplace=True)
p_values.plot.bar()

IndexError: ignored

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
 12  Happiness Category             158 non-null    category
dtypes: category(1), float64(9), int64(1), object(2)
memory usage: 15.2+ KB

In [36]:
numeric=data[['Happiness Rank','Happiness Score','Economy (GDP per Capita)','Family','Health (Life Expectancy)']]
categorical=data[['Country','Region','Happiness Category']]

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.drop('Economy (GDP per Capita)',axis=1),data['Economy (GDP per Capita)'],test_size=0.30,random_state=0)
X_train.shape,X_test.shape
newdata=pd.concat([numeric, categorical], axis=1)
print(newdata)
from sklearn.preprocessing import LabelEncoder
for col in newdata.columns:
  le=LabelEncoder()
  newdata[col]=le.fit_transform(newdata[col])
  print (newdata)

from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaled_data = scaler.fit_transform(newdata)

     Happiness Rank  Happiness Score  Economy (GDP per Capita)   Family  \
0                 1            7.587                   1.39651  1.34951
1                 2            7.561                   1.30232  1.40223
2                 3            7.527                   1.32548  1.36058
3                 4            7.522                   1.45900  1.33095
4                 5            7.427                   1.32629  1.32261
..              ...              ...                       ...      ...
153             154            3.465                   0.22208  0.77370
154             155            3.340                   0.28665  0.35386
155             156            3.006                   0.66320  0.47489
156             157            2.905                   0.01530  0.41587
157             158            2.839                   0.20868  0.13995

     Health (Life Expectancy)      Country                           Region  \
0                     0.94143  Switzerland                   Western Europe
1                     0.94784      Iceland                   Western Europe
2                     0.87464      Denmark                   Western Europe
3                     0.88521       Norway                   Western Europe
4                     0.90563       Canada                    North America
..                        ...          ...                              ...
153                   0.42864       Rwanda               Sub-Saharan Africa
154                   0.31910        Benin               Sub-Saharan Africa
155                   0.72193        Syria  Middle East and Northern Africa
156                   0.22396      Burundi               Sub-Saharan Africa
157                   0.28443         Togo               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)   Family  \
0                 0            7.587                   1.39651  1.34951
1                 1            7.561                   1.30232  1.40223
2                 2            7.527                   1.32548  1.36058
3                 3            7.522                   1.45900  1.33095
4                 4            7.427                   1.32629  1.32261
..              ...              ...                       ...      ...
153             152            3.465                   0.22208  0.77370
154             153            3.340                   0.28665  0.35386
155             154            3.006                   0.66320  0.47489
156             155            2.905                   0.01530  0.41587
157             156            2.839                   0.20868  0.13995

     Health (Life Expectancy)      Country                           Region  \
0                     0.94143  Switzerland                   Western Europe
1                     0.94784      Iceland                   Western Europe
2                     0.87464      Denmark                   Western Europe
3                     0.88521       Norway                   Western Europe
4                     0.90563       Canada                    North America
..                        ...          ...                              ...
153                   0.42864       Rwanda               Sub-Saharan Africa
154                   0.31910        Benin               Sub-Saharan Africa
155                   0.72193        Syria  Middle East and Northern Africa
156                   0.22396      Burundi               Sub-Saharan Africa
157                   0.28443         Togo               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)   Family  \
0                 0              156                   1.39651  1.34951
1                 1              155                   1.30232  1.40223
2                 2              154                   1.32548  1.36058
3                 3              153                   1.45900  1.33095
4                 4              152                   1.32629  1.32261
..              ...              ...                       ...      ...
153             152                4                   0.22208  0.77370
154             153                3                   0.28665  0.35386
155             154                2                   0.66320  0.47489
156             155                1                   0.01530  0.41587
157             156                0                   0.20868  0.13995

     Health (Life Expectancy)      Country                           Region  \
0                     0.94143  Switzerland                   Western Europe
1                     0.94784      Iceland                   Western Europe
2                     0.87464      Denmark                   Western Europe
3                     0.88521       Norway                   Western Europe
4                     0.90563       Canada                    North America
..                        ...          ...                              ...
153                   0.42864       Rwanda               Sub-Saharan Africa
154                   0.31910        Benin               Sub-Saharan Africa
155                   0.72193        Syria  Middle East and Northern Africa
156                   0.22396      Burundi               Sub-Saharan Africa
157                   0.28443         Togo               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)   Family  \
0                 0              156                       151  1.34951
1                 1              155                       136  1.40223
2                 2              154                       139  1.36058
3                 3              153                       153  1.33095
4                 4              152                       140  1.32261
..              ...              ...                       ...      ...
153             152                4                        13  0.77370
154             153                3                        21  0.35386
155             154                2                        51  0.47489
156             155                1                         1  0.41587
157             156                0                        11  0.13995

     Health (Life Expectancy)      Country                           Region  \
0                     0.94143  Switzerland                   Western Europe
1                     0.94784      Iceland                   Western Europe
2                     0.87464      Denmark                   Western Europe
3                     0.88521       Norway                   Western Europe
4                     0.90563       Canada                    North America
..                        ...          ...                              ...
153                   0.42864       Rwanda               Sub-Saharan Africa
154                   0.31910        Benin               Sub-Saharan Africa
155                   0.72193        Syria  Middle East and Northern Africa
156                   0.22396      Burundi               Sub-Saharan Africa
157                   0.28443         Togo               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)  Family  \
0                 0              156                       151     154
1                 1              155                       136     157
2                 2              154                       139     155
3                 3              153                       153     152
4                 4              152                       140     151
..              ...              ...                       ...     ...
153             152                4                        13      29
154             153                3                        21       3
155             154                2                        51      11
156             155                1                         1       8
157             156                0                        11       1

     Health (Life Expectancy)      Country                           Region  \
0                     0.94143  Switzerland                   Western Europe
1                     0.94784      Iceland                   Western Europe
2                     0.87464      Denmark                   Western Europe
3                     0.88521       Norway                   Western Europe
4                     0.90563       Canada                    North America
..                        ...          ...                              ...
153                   0.42864       Rwanda               Sub-Saharan Africa
154                   0.31910        Benin               Sub-Saharan Africa
155                   0.72193        Syria  Middle East and Northern Africa
156                   0.22396      Burundi               Sub-Saharan Africa
157                   0.28443         Togo               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)  Family  \
0                 0              156                       151     154
1                 1              155                       136     157
2                 2              154                       139     155
3                 3              153                       153     152
4                 4              152                       140     151
..              ...              ...                       ...     ...
153             152                4                        13      29
154             153                3                        21       3
155             154                2                        51      11
156             155                1                         1       8
157             156                0                        11       1

     Health (Life Expectancy)      Country                           Region  \
0                         148  Switzerland                   Western Europe
1                         150      Iceland                   Western Europe
2                         128      Denmark                   Western Europe
3                         132       Norway                   Western Europe
4                         140       Canada                    North America
..                        ...          ...                              ...
153                        36       Rwanda               Sub-Saharan Africa
154                        23        Benin               Sub-Saharan Africa
155                        86        Syria  Middle East and Northern Africa
156                        12      Burundi               Sub-Saharan Africa
157                        18         Togo               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)  Family  \
0                 0              156                       151     154
1                 1              155                       136     157
2                 2              154                       139     155
3                 3              153                       153     152
4                 4              152                       140     151
..              ...              ...                       ...     ...
153             152                4                        13      29
154             153                3                        21       3
155             154                2                        51      11
156             155                1                         1       8
157             156                0                        11       1

     Health (Life Expectancy)  Country                           Region  \
0                         148      135                   Western Europe
1                         150       58                   Western Europe
2                         128       37                   Western Europe
3                         132      105                   Western Europe
4                         140       24                    North America
..                        ...      ...                              ...
153                        36      118               Sub-Saharan Africa
154                        23       13               Sub-Saharan Africa
155                        86      136  Middle East and Northern Africa
156                        12       21               Sub-Saharan Africa
157                        18      141               Sub-Saharan Africa

    Happiness Category
0       High Happiness
1       High Happiness
2       High Happiness
3       High Happiness
4       High Happiness
..                 ...
153      Low Happiness
154      Low Happiness
155      Low Happiness
156      Low Happiness
157      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)  Family  \
0                 0              156                       151     154
1                 1              155                       136     157
2                 2              154                       139     155
3                 3              153                       153     152
4                 4              152                       140     151
..              ...              ...                       ...     ...
153             152                4                        13      29
154             153                3                        21       3
155             154                2                        51      11
156             155                1                         1       8
157             156                0                        11       1

     Health (Life Expectancy)  Country  Region Happiness Category
0                         148      135       9     High Happiness
1                         150       58       9     High Happiness
2                         128       37       9     High Happiness
3                         132      105       9     High Happiness
4                         140       24       5     High Happiness
..                        ...      ...     ...                ...
153                        36      118       8      Low Happiness
154                        23       13       8      Low Happiness
155                        86      136       4      Low Happiness
156                        12       21       8      Low Happiness
157                        18      141       8      Low Happiness

[158 rows x 8 columns]
     Happiness Rank  Happiness Score  Economy (GDP per Capita)  Family  \
0                 0              156                       151     154
1                 1              155                       136     157
2                 2              154                       139     155
3                 3              153                       153     152
4                 4              152                       140     151
..              ...              ...                       ...     ...
153             152                4                        13      29
154             153                3                        21       3
155             154                2                        51      11
156             155                1                         1       8
157             156                0                        11       1

     Health (Life Expectancy)  Country  Region  Happiness Category
0                         148      135       9                   0
1                         150       58       9                   0
2                         128       37       9                   0
3                         132      105       9                   0
4                         140       24       5                   0
..                        ...      ...     ...                 ...
153                        36      118       8                   1
154                        23       13       8                   1
155                        86      136       4                   1
156                        12       21       8                   1
157                        18      141       8                   1

[158 rows x 8 columns]

In [45]:
data = np.array(data[['Economy (GDP per Capita)','Family','Health (Life Expectancy)']])
cov_matrix = np.cov(data, bias=True)
print(cov_matrix)

IndexError: ignored

In [ ]:
sns.heatmap(cov_matrix, cmap='coolwarm', annot=True)

In [42]:
data['Happiness Score'].plot(kind='hist',title='Age',grid=True,hue='Country')
plt.show()

IndexError: ignored